### ISSUE TITLE
tensorboard doesn't appear to start

### ISSUE THREAD

**Issue by langley** [sbrunk/scala-deeplearn-examples#1]
I'm running tensorFlow/runMain io.brunk.examples.MnistMLP 
and I expected to be able to open http://127.0.0.1:6006 or http://localhost:6006 and see tensorboard. However, using chrome and then netstat, it doesn't look like tensorboard is starting. 

Is there something I need to do to kick off the process? 

TIA! By the way, YOUR EXAMPLES ROCK! 

- J

**Comment by sbrunk** [comment]
tensorboard should run if you have it on your PATH in the environment where sbt is run (i.e. by installing tensorflow via pip).
Does it work when you invoke it manually from the project dir during/after training?
```bash
$ tensorboard --logdir=tensorflow/temp/mnist-mlp/
```

**Comment by langley** [comment]
Yep, that was it! I'm trying to learn about TensorFlow w/out diving into Python. But this sort of illustrates that I'll probably have to do at least some of my initial introduction via the standard python based resources. 

Thanks again!
